services:
  nginx:
    image: nginx:latest
    container_name: mi_contenedor
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - testnetwork


networks:
  testnetwork:

